<?php

namespace Database\Seeders;

use App\Models\PortConfig;
use Illuminate\Database\Seeder;

class PortConfigSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $configs = [
            [
                'financia_year_id' => 1,
                'order' => 1,
                'taxtype_id' => 9,
                'code' => 'NFAT',
                'name' => 'No. of foreign passengers',
                'row_type' => 'dynamic',
                'value_calculated' => true,
                'col_type' => 'normal',
                'rate_applicable' => true,
                'rate_type' => 'fixed',
                'currency' => 'USD',
                'rate' => 40,
                'rate_usd' => 0,
                'active' => true,
            ],
            [
                'financia_year_id' => 1,
                'order' => 2,
                'taxtype_id' => 9,
                'code' => 'NLAT',
                'name' => 'No. of local passengers(Airport Tax)',
                'row_type' => 'dynamic',
                'value_calculated' => true,
                'col_type' => 'normal',
                'rate_applicable' => true,
                'rate_type' => 'fixed',
                'currency' => 'TZS',
                'rate' => 10000,
                'rate_usd' => 0,
                'active' => true,
            ],
            [
                'financia_year_id' => 1,
                'order' => 3,
                'taxtype_id' => 9,
                'code' => 'NFSF',
                'name' => 'No. of Foreign passengers',
                'row_type' => 'dynamic',
                'value_calculated' => true,
                'col_type' => 'normal',
                'rate_applicable' => true,
                'rate_type' => 'fixed',
                'currency' => 'USD',
                'rate' => 9,
                'rate_usd' => 0,
                'active' => true,
            ],
            [
                'financia_year_id' => 1,
                'order' => 4,
                'taxtype_id' => 9,
                'code' => 'NLSF',
                'name' => 'No. of local passengers(Safety fee)',
                'row_type' => 'dynamic',
                'value_calculated' => true,
                'col_type' => 'normal',
                'rate_applicable' => true,
                'rate_type' => 'fixed',
                'currency' => 'TZS',
                'rate' => 3000,
                'rate_usd' => 0,
                'active' => true,
            ],
            [
                'financia_year_id' => 1,
                'order' => 5,
                'taxtype_id' => 9,
                'code' => 'IT',
                'name' => 'Imfrastracture Tax',
                'row_type' => 'dynamic',
                'value_calculated' => true,
                'col_type' => 'normal',
                'rate_applicable' => true,
                'rate_type' => 'fixed',
                'currency' => 'TZS',
                'rate' => 2000,
                'rate_usd' => 0,
                'active' => true,
            ],
            [
                'financia_year_id' => 1,
                'order' => 6,
                'taxtype_id' => 9,
                'code' => 'TLATZS',
                'name' => 'Total Amount Fee Due(TZS)',
                'row_type' => 'unremovable',
                'col_type' => 'subtotal',
                'value_calculated' => true,
                'formular' => 'NLAT+NLSF+IT',
                'active' => true,
            ],
            [
                'financia_year_id' => 1,
                'order' => 7,
                'taxtype_id' => 9,
                'code' => 'TLAUSD',
                'name' => 'Total Amount Fee Due (US$)',
                'row_type' => 'unremovable',
                'col_type' => 'subtotal',
                'value_calculated' => true,
                'formular' => 'NFAT+NFSF',
                'active' => true,
            ],
            //   Sea Port & Transport Tax
            [
                'financia_year_id' => 1,
                'order' => 8,
                'taxtype_id' => 10,
                'code' => 'NFSP',
                'name' => 'No. of foreign passengers',
                'row_type' => 'dynamic',
                'value_calculated' => true,
                'col_type' => 'normal',
                'rate_applicable' => true,
                'rate_type' => 'fixed',
                'currency' => 'USD',
                'rate' => 10,
                'rate_usd' => 0,
                'active' => true,
            ],
            [
                'financia_year_id' => 1,
                'order' => 9,
                'taxtype_id' => 10,
                'code' => 'NLTM',
                'name' => 'No. of local passengers(ZNZ - T/M)',
                'row_type' => 'dynamic',
                'value_calculated' => true,
                'col_type' => 'normal',
                'rate_applicable' => true,
                'rate_type' => 'fixed',
                'currency' => 'TZS',
                'rate' => 2000,
                'rate_usd' => 0,
                'active' => true,
            ],
            [
                'financia_year_id' => 1,
                'order' => 10,
                'taxtype_id' => 10,
                'code' => 'NLZNZ',
                'name' => 'No. of local passengers (ZNZ - ZNZ)',
                'row_type' => 'dynamic',
                'value_calculated' => true,
                'col_type' => 'normal',
                'rate_applicable' => true,
                'rate_type' => 'fixed',
                'currency' => 'TZS',
                'rate' => 1000,
                'rate_usd' => 0,
                'active' => true,
            ],
            [
                'financia_year_id' => 1,
                'order' => 11,
                'taxtype_id' => 10,
                'code' => 'ITZNZ',
                'name' => 'Imfrastructure Tax (ZNZ - ZNZ)',
                'row_type' => 'dynamic',
                'value_calculated' => true,
                'col_type' => 'normal',
                'rate_applicable' => true,
                'rate_type' => 'fixed',
                'currency' => 'TZS',
                'rate' => 1000,
                'rate_usd' => 0,
                'active' => true,
            ],
            [
                'financia_year_id' => 1,
                'order' => 12,
                'taxtype_id' => 10,
                'code' => 'ITTM',
                'name' => 'Imfrastructure Tax (ZNZ - T/M)',
                'row_type' => 'dynamic',
                'value_calculated' => true,
                'col_type' => 'normal',
                'rate_applicable' => true,
                'rate_type' => 'fixed',
                'currency' => 'TZS',
                'rate' => 2000,
                'rate_usd' => 0,
                'active' => true,
            ],
            [
                'financia_year_id' => 1,
                'order' => 13,
                'taxtype_id' => 10,
                'code' => 'NSUS',
                'name' => 'Value of Net Sales (US$)',
                'row_type' => 'dynamic',
                'value_calculated' => true,
                'col_type' => 'normal',
                'rate_applicable' => true,
                'rate_type' => 'percentage',
                'currency' => 'TZS',
                'rate' => 8,
                'rate_usd' => 0,
                'active' => true,
            ],
            [
                'financia_year_id' => 1,
                'order' => 14,
                'taxtype_id' => 10,
                'code' => 'NSTZ',
                'name' => 'Value of Net Sales (TZS)',
                'row_type' => 'dynamic',
                'value_calculated' => true,
                'col_type' => 'normal',
                'rate_applicable' => true,
                'rate_type' => 'percentage',
                'currency' => 'TZS',
                'rate' => 8,
                'rate_usd' => 0,
                'active' => true,
            ],
            [
                'financia_year_id' => 1,
                'order' => 15,
                'taxtype_id' => 10,
                'code' => 'TLSTZS',
                'name' => 'Total Amount Fee Due(TZS)',
                'row_type' => 'unremovable',
                'col_type' => 'subtotal',
                'value_calculated' => true,
                'formular' => 'NLTM+NLZNZ+ITZNZ+ITTM+NSTZ',
                'active' => true,
            ],
            [
                'financia_year_id' => 1,
                'order' => 16,
                'taxtype_id' => 10,
                'code' => 'TLSUSD',
                'name' => 'Total Amount Fee Due (US$)',
                'row_type' => 'unremovable',
                'col_type' => 'subtotal',
                'value_calculated' => true, 
                'formular' => 'NFSP+NSUS',
                'active' => true,
            ],
        ];

        foreach ($configs as $config) {
            PortConfig::updateOrCreate($config);
        }

    }
}
