<?php

namespace Database\Seeders\Tra;

use App\Models\Tra\TraVehicleColor;
use Illuminate\Database\Seeder;

class VehicleColorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $colors = array(
            array("code"=>"1", "name"=>"Black Matteg"),
            array("code"=>"2", "name"=>"Pink/Purplek"),
            array("code"=>"3", "name"=>"Brown/Black/White"),
            array("code"=>"4", "name"=>"VINTAGE BROWN PEARL CS"),
            array("code"=>"5", "name"=>"Navy Bluebl"),
            array("code"=>"6", "name"=>"Blue/Greyjj"),
            array("code"=>"7", "name"=>"Silver/Wine/Red"),
            array("code"=>"8", "name"=>"Dark Grey Meftallic"),
            array("code"=>"9", "name"=>"Black/Greyb"),
            array("code"=>"10", "name"=>"Light Gun Metallic"),
            array("code"=>"11", "name"=>"Champagne Silver"),
            array("code"=>"12", "name"=>"Armada Gold"),
            array("code"=>"13", "name"=>"Ivory"),
            array("code"=>"14", "name"=>"Tream"),
            array("code"=>"15", "name"=>"Limestone"),
            array("code"=>"16", "name"=>"Pearl Metallic"),
            array("code"=>"17", "name"=>"Red/Black"),
            array("code"=>"18", "name"=>"Maroon/Beige"),
            array("code"=>"19", "name"=>"Sparling Black"),
            array("code"=>"20", "name"=>"Trim.."),
            array("code"=>"21", "name"=>"Emerald Black"),
            array("code"=>"22", "name"=>"Cream Red"),
            array("code"=>"23", "name"=>"Yellow Metallic"),
            array("code"=>"24", "name"=>"Red Winer"),
            array("code"=>"25", "name"=>"Dark Blue Metallic"),
            array("code"=>"26", "name"=>"Windjammer Blue"),
            array("code"=>"27", "name"=>"Arizona Cream"),
            array("code"=>"28", "name"=>"Silver/Yellow"),
            array("code"=>"29", "name"=>"Blue/Orange"),
            array("code"=>"30", "name"=>"Bluish/Silver"),
            array("code"=>"31", "name"=>"Avalon Blue"),
            array("code"=>"32", "name"=>"White/Black/Yellow"),
            array("code"=>"33", "name"=>"Red/White/Yellow"),
            array("code"=>"34", "name"=>"Red/Brown"),
            array("code"=>"35", "name"=>"Wine Silver"),
            array("code"=>"36", "name"=>"Montpellier Red"),
            array("code"=>"37", "name"=>"Omir"),
            array("code"=>"38", "name"=>"Blue/Cream"),
            array("code"=>"39", "name"=>"Dark Green Mint Silver Blue"),
            array("code"=>"40", "name"=>"Charry Red/Light Brown"),
            array("code"=>"41", "name"=>"Arogonite Blue"),
            array("code"=>"42", "name"=>"Beluga Black"),
            array("code"=>"43", "name"=>"Chawton White"),
            array("code"=>"44", "name"=>"Sand Stone/Warm Gray"),
            array("code"=>"45", "name"=>"Fairy White"),
            array("code"=>"46", "name"=>"Light Grey"),
            array("code"=>"47", "name"=>"White/Cream/Blue"),
            array("code"=>"48", "name"=>"Ebony Black"),
            array("code"=>"49", "name"=>"Tanzanite Blue"),
            array("code"=>"50", "name"=>"Alabaster White"),
            array("code"=>"51", "name"=>"Melanite Black"),
            array("code"=>"52", "name"=>"Green Black"),
            array("code"=>"53", "name"=>"Obsidian Black"),
            array("code"=>"54", "name"=>"Tealite Blue"),
            array("code"=>"55", "name"=>"Titanite Red"),
            array("code"=>"56", "name"=>"Travertine Beige"),
            array("code"=>"57", "name"=>"Cubanite Silver"),
            array("code"=>"58", "name"=>"Brilliant Silver"),
            array("code"=>"59", "name"=>"Tektite Grey"),
            array("code"=>"60", "name"=>"Andradite Green"),
            array("code"=>"61", "name"=>"Aragonite Blue"),
            array("code"=>"62", "name"=>"Spectra Red"),
            array("code"=>"63", "name"=>"Light Aqua M.Opal"),
            array("code"=>"64", "name"=>"Light Aqua"),
            array("code"=>"65", "name"=>"Light Yellow"),
            array("code"=>"66", "name"=>"Willow Green"),
            array("code"=>"67", "name"=>"Beige/Blue/Silver"),
            array("code"=>"68", "name"=>"Bishop Blue"),
            array("code"=>"69", "name"=>"Green/Grey/Yellow"),
            array("code"=>"70", "name"=>"Beige/Shadow Grey"),
            array("code"=>"71", "name"=>"Sahara Red"),
            array("code"=>"72", "name"=>"Torquise Blue"),
            array("code"=>"73", "name"=>"Ivory White"),
            array("code"=>"74", "name"=>"Beige Shadow"),
            array("code"=>"75", "name"=>"Blue/Pink/Yellow"),
            array("code"=>"76", "name"=>"Black Blue"),
            array("code"=>"77", "name"=>"Blue/Light Blue/Black"),
            array("code"=>"78", "name"=>"Cobar Blue"),
            array("code"=>"79", "name"=>"Capric Blue"),
            array("code"=>"80", "name"=>"Deep Maroon Metallic"),
            array("code"=>"81", "name"=>"Roman Bronze"),
            array("code"=>"82", "name"=>"Cream/Pupple/Maroon"),
            array("code"=>"83", "name"=>"Light Grey Metallic"),
            array("code"=>"84", "name"=>"Marine Blue"),
            array("code"=>"85", "name"=>"Blue/Silver/Brown"),
            array("code"=>"86", "name"=>"Black/Brown"),
            array("code"=>"87", "name"=>"Summer Beige"),
            array("code"=>"88", "name"=>"Chamios"),
            array("code"=>"89", "name"=>"Lavenda Mica Metallic"),
            array("code"=>"90", "name"=>"Warm Grey Pearl Metallic"),
            array("code"=>"91", "name"=>"Olive"),
            array("code"=>"92", "name"=>"Epson Green"),
            array("code"=>"93", "name"=>"Summer Red"),
            array("code"=>"94", "name"=>"Summer White"),
            array("code"=>"95", "name"=>"Metallic Silver Black"),
            array("code"=>"96", "name"=>"White/Blue/Summer White"),
            array("code"=>"97", "name"=>"Maroon/Blue"),
            array("code"=>"98", "name"=>"White/Green/Black"),
            array("code"=>"99", "name"=>"White/Red/Blue"),
            array("code"=>"100", "name"=>"Yellow/L.Blue/Silver"),
            array("code"=>"101", "name"=>"White/Blue/Silver"),
            array("code"=>"102", "name"=>"Bright Blue M."),
            array("code"=>"103", "name"=>"Green Beige"),
            array("code"=>"104", "name"=>"Light Beige Metallic"),
            array("code"=>"105", "name"=>"Sea Green/Grass Green"),
            array("code"=>"106", "name"=>"Blue/Grey/White"),
            array("code"=>"107", "name"=>"White Catalytic"),
            array("code"=>"108", "name"=>"Green/Grey/Beige"),
            array("code"=>"109", "name"=>"Two Tone"),
            array("code"=>"110", "name"=>"Beige/Cream"),
            array("code"=>"111", "name"=>"Light Tan"),
            array("code"=>"112", "name"=>"Maroon/Light Green"),
            array("code"=>"113", "name"=>"Purple/Grey"),
            array("code"=>"114", "name"=>"Light Grey/Ivory"),
            array("code"=>"115", "name"=>"Cream/Chocolate"),
            array("code"=>"116", "name"=>"Pink/Chocolate"),
            array("code"=>"117", "name"=>"Glacier Green"),
            array("code"=>"118", "name"=>"Blue Pearl Silver Metallic"),
            array("code"=>"119", "name"=>"Dark Blue/Grey"),
            array("code"=>"120", "name"=>"Intense Blue"),
            array("code"=>"121", "name"=>"MONACOBLAU METALLIC "),
            array("code"=>"122", "name"=>"Avalon"),
            array("code"=>"123", "name"=>"White Gold"),
            array("code"=>"124", "name"=>"Shiraz Red Mica"),
            array("code"=>"125", "name"=>"White Gold"),
            array("code"=>"126", "name"=>"Tobacco Leaf"),
            array("code"=>"127", "name"=>"Maroon Red"),
            array("code"=>"128", "name"=>"Red/Maroon"),
            array("code"=>"129", "name"=>"Red/Grey/Beige"),
            array("code"=>"130", "name"=>"Grey Metallic / Opal"),
            array("code"=>"131", "name"=>"Red/Light Violet/Gold"),
            array("code"=>"132", "name"=>"Sandal Wood"),
            array("code"=>"133", "name"=>"Yellow/Green/Silver"),
            array("code"=>"134", "name"=>"Light Gold/Greyish/Beige"),
            array("code"=>"135", "name"=>"Sand Glow"),
            array("code"=>"136", "name"=>"Prem Green"),
            array("code"=>"137", "name"=>"Mojave Brown"),
            array("code"=>"138", "name"=>"Peiwinkle Black"),
            array("code"=>"139", "name"=>"Blue/Light Blue/Red/Orange"),
            array("code"=>"140", "name"=>"Flaxen Mica Metallic"),
            array("code"=>"141", "name"=>"Yellow Beige"),
            array("code"=>"142", "name"=>"Dark Green Pearl Metallic"),
            array("code"=>"143", "name"=>"Peacock"),
            array("code"=>"144", "name"=>"White Rose"),
            array("code"=>"145", "name"=>"Silver two tone"),
            array("code"=>"146", "name"=>"Purple Blue"),
            array("code"=>"147", "name"=>"Dark Green /Yellowish /Silver "),
            array("code"=>"148", "name"=>"Grey Mopal"),
            array("code"=>"149", "name"=>"Astro Silver"),
            array("code"=>"150", "name"=>"Us-Aquarius"),
            array("code"=>"151", "name"=>"Beige/Blue"),
            array("code"=>"152", "name"=>"Flaxen Metalic Opel"),
            array("code"=>"153", "name"=>"Jet Black"),
            array("code"=>"154", "name"=>"Anthracite"),
            array("code"=>"155", "name"=>"Silver Satellite"),
            array("code"=>"156", "name"=>"Red Oxide"),
            array("code"=>"157", "name"=>"White/Beige/Red Oxide Strips"),
            array("code"=>"158", "name"=>"Vini"),
            array("code"=>"159", "name"=>"Olive Grayish Beige"),
            array("code"=>"160", "name"=>"Silver Beige"),
            array("code"=>"161", "name"=>"Smoked Silver"),
            array("code"=>"162", "name"=>"Vermillion"),
            array("code"=>"163", "name"=>"Grayish Beige"),
            array("code"=>"164", "name"=>"Savarin White"),
            array("code"=>"165", "name"=>"Jade"),
            array("code"=>"166", "name"=>"Warm Grey"),
            array("code"=>"167", "name"=>"Marine"),
            array("code"=>"168", "name"=>"Lemon Green"),
            array("code"=>"169", "name"=>"Tan"),
            array("code"=>"170", "name"=>"Green/Silver/Cream"),
            array("code"=>"171", "name"=>"White/Grey Metallic"),
            array("code"=>"172", "name"=>"Chianti Red Pearl"),
            array("code"=>"173", "name"=>"Clover Green Pearl"),
            array("code"=>"174", "name"=>"Mojave Mist Pearl"),
            array("code"=>"175", "name"=>"Satin Silver Metallic"),
            array("code"=>"176", "name"=>"Premium White Pearl"),
            array("code"=>"177", "name"=>"Light Brown"),
            array("code"=>"178", "name"=>"Dark/Light Green"),
            array("code"=>"179", "name"=>"asdasd"),
            array("code"=>"180", "name"=>"Sky Blueffff"),
            array("code"=>"181", "name"=>"Golden & Black"),
            array("code"=>"182", "name"=>"Tritofff"),
            array("code"=>"183", "name"=>"Light Brown Metallic"),
            array("code"=>"184", "name"=>"Light Bearsrrtrtr"),
            array("code"=>"185", "name"=>"White/Red/Grey"),
            array("code"=>"186", "name"=>"Cocoon Whitet"),
            array("code"=>"187", "name"=>"Dark Blue/ Sparkling Silver"),
            array("code"=>"188", "name"=>"White/Dark Greyt"),
            array("code"=>"189", "name"=>"Asian Greenfff"),
            array("code"=>"190", "name"=>"Silver Purplewewe"),
            array("code"=>"191", "name"=>"Silver Purple/Silver Light Purpfffle"),
            array("code"=>"192", "name"=>"White/Scorp Green"),
            array("code"=>"193", "name"=>"Dyscaya Blue"),
            array("code"=>"194", "name"=>"Black/Green"),
            array("code"=>"195", "name"=>"Fino Red"),
            array("code"=>"196", "name"=>"Red/White/Green"),
            array("code"=>"197", "name"=>"Red/White/Cream"),
            array("code"=>"198", "name"=>"White/Lavender"),
            array("code"=>"199", "name"=>"dddddd"),
            array("code"=>"200", "name"=>"Bright Greenfff"),
            array("code"=>"201", "name"=>"Orange/Grey"),
            array("code"=>"202", "name"=>"Maroon/Coca Red"),
            array("code"=>"203", "name"=>"Green Aspen"),
            array("code"=>"204", "name"=>"Orange/Black"),
            array("code"=>"205", "name"=>"Gulf Blue"),
            array("code"=>"206", "name"=>"Scope Green"),
            array("code"=>"207", "name"=>"Scorp Green"),
            array("code"=>"208", "name"=>"Black Metallic Beirge"),
            array("code"=>"209", "name"=>"Deep Blue Pearl"),
            array("code"=>"210", "name"=>"Light Brown/Dark Brown"),
            array("code"=>"211", "name"=>"Sand"),
            array("code"=>"212", "name"=>"Grey/Light Grey"),
            array("code"=>"213", "name"=>"Red/Light Gold"),
            array("code"=>"214", "name"=>"Yellow/Pink"),
            array("code"=>"215", "name"=>"Gold Rush"),
            array("code"=>"216", "name"=>"Greenish Black"),
            array("code"=>"217", "name"=>"Dark Beige/Light Beige"),
            array("code"=>"218", "name"=>"Mushroom"),
            array("code"=>"219", "name"=>"Alpine Fern"),
            array("code"=>"220", "name"=>"Beige/Black"),
            array("code"=>"221", "name"=>"Blue/Gold"),
            array("code"=>"222", "name"=>"Cream/White/Ivory"),
            array("code"=>"223", "name"=>"Deep Buff"),
            array("code"=>"224", "name"=>"Pal"),
            array("code"=>"225", "name"=>"Orange/White/Black"),
            array("code"=>"226", "name"=>"L.Orange/Blue/White"),
            array("code"=>"227", "name"=>"English Silver"),
            array("code"=>"228", "name"=>"Blue/Black/Yellow"),
            array("code"=>"229", "name"=>"White Sky Blue"),
            array("code"=>"230", "name"=>"Platinum Grey"),
            array("code"=>"231", "name"=>"Black/Yellow"),
            array("code"=>"232", "name"=>"Cream Sandstone"),
            array("code"=>"233", "name"=>"Light Green/Dark Green"),
            array("code"=>"234", "name"=>"Lazurite Blue"),
            array("code"=>"235", "name"=>"Cubanite Silver"),
            array("code"=>"236", "name"=>"Iridium Silver"),
            array("code"=>"237", "name"=>"Carneol Red"),
            array("code"=>"238", "name"=>"Andradite Green"),
            array("code"=>"239", "name"=>"White"),
            array("code"=>"240", "name"=>"Blue"),
            array("code"=>"241", "name"=>"Yellow"),
            array("code"=>"242", "name"=>"Red"),
            array("code"=>"243", "name"=>"Green"),
            array("code"=>"244", "name"=>"Black"),
            array("code"=>"245", "name"=>"Brown"),
            array("code"=>"246", "name"=>"Grey"),
            array("code"=>"247", "name"=>"Pink"),
            array("code"=>"248", "name"=>"Multicolour"),
            array("code"=>"249", "name"=>"Maroon"),
            array("code"=>"250", "name"=>"Mustard"),
            array("code"=>"251", "name"=>"Navy"),
            array("code"=>"252", "name"=>"Orange"),
            array("code"=>"253", "name"=>"Peach"),
            array("code"=>"254", "name"=>"Cream"),
            array("code"=>"255", "name"=>"Purple"),
            array("code"=>"256", "name"=>"Burgundy"),
            array("code"=>"257", "name"=>"Silver"),
            array("code"=>"258", "name"=>"Turquoise"),
            array("code"=>"259", "name"=>"Beige"),
            array("code"=>"260", "name"=>"Charcoal"),
            array("code"=>"261", "name"=>"Gold"),
            array("code"=>"262", "name"=>"Champagne"),
            array("code"=>"263", "name"=>"Light Green Metallic"),
            array("code"=>"264", "name"=>"Dark Green Mica Metallic"),
            array("code"=>"265", "name"=>"Dark Blue"),
            array("code"=>"266", "name"=>"White/Dark Greish Blue"),
            array("code"=>"267", "name"=>"White/Lavender"),
            array("code"=>"268", "name"=>"White Turquoise"),
            array("code"=>"269", "name"=>"Silver Metallic"),
            array("code"=>"270", "name"=>"Dark Grey Mica Metallic"),
            array("code"=>"271", "name"=>"Dark Red Mica"),
            array("code"=>"272", "name"=>"Champagne Mica Metallic"),
            array("code"=>"273", "name"=>"Dark Green Mica"),
            array("code"=>"274", "name"=>"Light Green Mica Metallic"),
            array("code"=>"275", "name"=>"Dark Blue Mica Metallic"),
            array("code"=>"276", "name"=>"Warm Silver Metallic"),
            array("code"=>"277", "name"=>"Gold Mica Metallic"),
            array("code"=>"278", "name"=>"Grey Metallic"),
            array("code"=>"279", "name"=>"Blue Mica"),
            array("code"=>"280", "name"=>"Blue Metallic"),
            array("code"=>"281", "name"=>"Red Mica Metallic"),
            array("code"=>"282", "name"=>"Brown Metallic"),
            array("code"=>"283", "name"=>"Beige"),
            array("code"=>"284", "name"=>"Green Metallic Opal "),
            array("code"=>"285", "name"=>"Beige  Metallic"),
            array("code"=>"286", "name"=>"Light Rose Mica"),
            array("code"=>"287", "name"=>"Pearly White"),
            array("code"=>"288", "name"=>"Light Gold/Beige"),
            array("code"=>"289", "name"=>"Sophia White"),
            array("code"=>"290", "name"=>"White Gold"),
            array("code"=>"291", "name"=>"Metallic Green"),
            array("code"=>"292", "name"=>"Grey Beige"),
            array("code"=>"293", "name"=>"White/Green"),
            array("code"=>"294", "name"=>"Red/White"),
            array("code"=>"295", "name"=>"Orange/Summer Blue"),
            array("code"=>"296", "name"=>"Silver /Green"),
            array("code"=>"297", "name"=>"White Beige"),
            array("code"=>"298", "name"=>"White/Blue/Red"),
            array("code"=>"299", "name"=>"White/Blue"),
            array("code"=>"300", "name"=>"White/Red"),
            array("code"=>"301", "name"=>"Black/Silver"),
            array("code"=>"302", "name"=>"Sparkling Silver"),
            array("code"=>"303", "name"=>"Light Gold/Gray"),
            array("code"=>"304", "name"=>"Green/Gray"),
            array("code"=>"305", "name"=>"Light Gold/Gray"),
            array("code"=>"306", "name"=>"Brown/Gray"),
            array("code"=>"307", "name"=>"Red/Gray"),
            array("code"=>"308", "name"=>"Blue/Silver"),
            array("code"=>"309", "name"=>"Burning Red"),
            array("code"=>"310", "name"=>"Dark Blue Pearl"),
            array("code"=>"311", "name"=>"Misty Green Metallic"),
            array("code"=>"312", "name"=>"Titanium Silver Metallic"),
            array("code"=>"313", "name"=>"Silver/Light Purple"),
            array("code"=>"314", "name"=>"Beige/White"),
            array("code"=>"315", "name"=>"White/Blue"),
            array("code"=>"316", "name"=>"White/Orange"),
            array("code"=>"317", "name"=>"Light Greenish Silver "),
            array("code"=>"318", "name"=>"Diamond Silver"),
            array("code"=>"319", "name"=>"Sherbert Silver / Purpish Silver "),
            array("code"=>"320", "name"=>"Black/Sparkling Silver "),
            array("code"=>"321", "name"=>"Silver/Blue"),
            array("code"=>"322", "name"=>"Dark Green"),
            array("code"=>"323", "name"=>"Grey / Cream"),
            array("code"=>"324", "name"=>"Grey/White"),
            array("code"=>"325", "name"=>"Metallic"),
            array("code"=>"326", "name"=>"Dark Green / Silver"),
            array("code"=>"327", "name"=>"Red/Silver"),
            array("code"=>"328", "name"=>"Wine Green"),
            array("code"=>"329", "name"=>"Pearl"),
            array("code"=>"330", "name"=>"Blue/Red"),
            array("code"=>"331", "name"=>"Green/Red"),
            array("code"=>"332", "name"=>"Blue/Yellow"),
            array("code"=>"333", "name"=>"Black Metallic"),
            array("code"=>"334", "name"=>"Firn White"),
            array("code"=>"335", "name"=>"Graphite"),
            array("code"=>"336", "name"=>"Gray Meca"),
            array("code"=>"337", "name"=>"Zambezi Silver"),
            array("code"=>"338", "name"=>"White/Maroon"),
            array("code"=>"339", "name"=>"Maroon /Cream"),
            array("code"=>"340", "name"=>"Super White"),
            array("code"=>"341", "name"=>"Grey / Silver"),
            array("code"=>"342", "name"=>"White/Yellow"),
            array("code"=>"343", "name"=>"Maroon/Yellow"),
            array("code"=>"344", "name"=>"Green/Sky Blue"),
            array("code"=>"345", "name"=>"Blue/Orange/Silver"),
            array("code"=>"346", "name"=>"Chawton White Solid"),
            array("code"=>"347", "name"=>"Oslo Blue Mica talic"),
            array("code"=>"348", "name"=>"Zambezi Silver Metal"),
            array("code"=>"349", "name"=>"Yellow/ Green"),
            array("code"=>"350", "name"=>"Green Metallic"),
            array("code"=>"351", "name"=>"Metallic Red"),
            array("code"=>"352", "name"=>"White/Green/Blue"),
            array("code"=>"353", "name"=>"White/Blue/Black"),
            array("code"=>"354", "name"=>"Aventurine Orange"),
            array("code"=>"355", "name"=>"Satellite Silver "),
            array("code"=>"356", "name"=>"Light Blue"),
            array("code"=>"357", "name"=>"Green/Orange"),
            array("code"=>"358", "name"=>"Beige/Brown"),
            array("code"=>"359", "name"=>"Silver/Maroon/Black"),
            array("code"=>"360", "name"=>"White/Green/Silver"),
            array("code"=>"361", "name"=>"White/Silver"),
            array("code"=>"362", "name"=>"White/Black"),
            array("code"=>"363", "name"=>"Red"),
            array("code"=>"364", "name"=>"Wine Red"),
            array("code"=>"365", "name"=>"Wine Red Two Tone"),
            array("code"=>"366", "name"=>"Light Green"),
            array("code"=>"367", "name"=>"Dark Green/Beige"),
            array("code"=>"368", "name"=>"Blue/Gold"),
            array("code"=>"369", "name"=>"Violet"),
            array("code"=>"370", "name"=>"Gold/Grey"),
            array("code"=>"371", "name"=>"L/Aquam Opal "),
            array("code"=>"372", "name"=>"Dark Grey"),
            array("code"=>"373", "name"=>"Light Beige"),
            array("code"=>"374", "name"=>"White/Orange /Silver"),
            array("code"=>"375", "name"=>"Timber Green"),
            array("code"=>"376", "name"=>"Green/Silver Metallic"),
            array("code"=>"377", "name"=>"Dark Green / Silver Metallic"),
            array("code"=>"378", "name"=>"White/Red/Silver"),
            array("code"=>"379", "name"=>"Red/Maroon/White"),
            array("code"=>"380", "name"=>"White/Red/Silver"),
            array("code"=>"381", "name"=>"Dark Green/Brown"),
            array("code"=>"382", "name"=>"Tektite Grey"),
            array("code"=>"383", "name"=>"Caledonian Blue"),
            array("code"=>"384", "name"=>"Biaritz Blue"),
            array("code"=>"385", "name"=>"Grey/Blue"),
            array("code"=>"386", "name"=>"Blue/Grey"),
            array("code"=>"387", "name"=>"Latraviata"),
            array("code"=>"388", "name"=>"Maroon/Silver"),
            array("code"=>"389", "name"=>"White/Brown"),
            array("code"=>"390", "name"=>"Black/Red/White"),
            array("code"=>"391", "name"=>"White/Black/Silver"),
            array("code"=>"392", "name"=>"Niagra Green"),
            array("code"=>"393", "name"=>"Flexn Mica Met"),
            array("code"=>"394", "name"=>"Fraser Beige"),
            array("code"=>"395", "name"=>"Read/Gold"),
            array("code"=>"396", "name"=>"Cerise Red/Cool Gray"),
            array("code"=>"397", "name"=>"Bright Silver"),
            array("code"=>"398", "name"=>"Red/Golden"),
            array("code"=>"399", "name"=>"Golden"),
            array("code"=>"400", "name"=>"Light Stone"),
            array("code"=>"401", "name"=>"Broken White"),
            array("code"=>"402", "name"=>"Brown/Blue"),
            array("code"=>"403", "name"=>"Other Silver"),
            array("code"=>"404", "name"=>"Green/Broken W hite"),
            array("code"=>"405", "name"=>"White/Yellow/Silver"),
            array("code"=>"406", "name"=>"Blue/Yellow/Silver"),
            array("code"=>"407", "name"=>"Black/Maroon"),
            array("code"=>"408", "name"=>"Marine Green"),
            array("code"=>"409", "name"=>"Light Blue Metallic"),
            array("code"=>"410", "name"=>"Red/Beige"),
            array("code"=>"411", "name"=>"Dark Brown  Metallic"),
            array("code"=>"412", "name"=>"White/Purple"),
            array("code"=>"413", "name"=>"White Taire"),
            array("code"=>"414", "name"=>"Forest Green"),
            array("code"=>"415", "name"=>"Nimbus"),
            array("code"=>"416", "name"=>"Biege /Blue"),
            array("code"=>"417", "name"=>"Pearly Brown"),
            array("code"=>"418", "name"=>"Green/Orange/Red/Yellow"),
            array("code"=>"419", "name"=>"Brown/Silver"),
            array("code"=>"420", "name"=>"Yellow/Blue/White"),
            array("code"=>"421", "name"=>"White/Cream"),
            array("code"=>"422", "name"=>"Golden/Brown"),
            array("code"=>"423", "name"=>"Dark/Light Blue"),
            array("code"=>"424", "name"=>"Obsidian Black"),
            array("code"=>"425", "name"=>"Gold Metalllic"),
            array("code"=>"426", "name"=>"Yellow/Red"),
            array("code"=>"427", "name"=>"Gun Metallic"),
            array("code"=>"428", "name"=>"Green Cream"),
            array("code"=>"429", "name"=>"Green/Golden"),
            array("code"=>"430", "name"=>"Chalcedony Blue"),
            array("code"=>"431", "name"=>"Silver/Golden"),
            array("code"=>"432", "name"=>"Golden/Yellow"),
            array("code"=>"433", "name"=>"White/Pink"),
            array("code"=>"434", "name"=>"Cream/Brown"),
            array("code"=>"435", "name"=>"Qmik"),
            array("code"=>"436", "name"=>"Light Gold"),
            array("code"=>"437", "name"=>"Maroon/Golden"),
            array("code"=>"438", "name"=>"Metallic/Green/Blue"),
            array("code"=>"439", "name"=>"Desert Glow"),
            array("code"=>"440", "name"=>"Dark Green Metallic"),
            array("code"=>"441", "name"=>"Dark Blue Metallic"),
            array("code"=>"442", "name"=>"Golden Beige"),
            array("code"=>"443", "name"=>"Maroon Metallic"),
            array("code"=>"444", "name"=>"Maroon Grey"),
            array("code"=>"445", "name"=>"Desert Wind"),
            array("code"=>"446", "name"=>"Bluish Green"),
            array("code"=>"447", "name"=>"Dark Blue/Stika Red"),
            array("code"=>"448", "name"=>"Wine Red/Silver Metallic"),
            array("code"=>"449", "name"=>"Blue/Green"),
            array("code"=>"450", "name"=>"Alpine White"),
            array("code"=>"451", "name"=>"Clay Metallic"),
            array("code"=>"452", "name"=>"Black 2 tone"),
            array("code"=>"453", "name"=>"Yellow/Brown"),
            array("code"=>"454", "name"=>"White/Tarquoise"),
            array("code"=>"455", "name"=>"Cyan Metallic"),
            array("code"=>"456", "name"=>"Oster Silver"),
            array("code"=>"457", "name"=>"Ocean Blue"),
            array("code"=>"458", "name"=>"Tonic Blue"),
            array("code"=>"459", "name"=>"Greyish Mica Metallic"),
            array("code"=>"460", "name"=>"Magenta"),
            array("code"=>"461", "name"=>"Red/Yellow/Blue/Green"),
            array("code"=>"462", "name"=>"Atacama Sand"),
            array("code"=>"463", "name"=>"Bronze"),
            array("code"=>"464", "name"=>"Pearly Black"),
            array("code"=>"465", "name"=>"Dark Purple/Pearly Mettalic"),
            array("code"=>"466", "name"=>"Keswick Green"),
            array("code"=>"467", "name"=>"Ash Grey"),
            array("code"=>"475", "name"=>"Missieg Metallic"),
            array("code"=>"476", "name"=>"Bright Greenfff"),
            array("code"=>"477", "name"=>"fffffff"),
            array("code"=>"478", "name"=>"Cocoon Whitet"),
            array("code"=>"479", "name"=>"Arctic White"),
            array("code"=>"480", "name"=>"Quartz Brown Metallic"),
            array("code"=>"481", "name"=>"Cool Silver Metallic"),
            array("code"=>"482", "name"=>"Titanium gray"),
            array("code"=>"483", "name"=>"Ruby Black Metallic"),
            array("code"=>"484", "name"=>"white pearl cs"),
            array("code"=>"485", "name"=>"attitude black"),
            array("code"=>"486", "name"=>"dark red mica"),
            array("code"=>"487", "name"=>"Dark Silver"),
            array("code"=>"488", "name"=>"light blue mica"),
            array("code"=>"489", "name"=>"bronze mm"),
            array("code"=>"490", "name"=>"dark brown mm"),
            array("code"=>"491", "name"=>"white/lavender"),
            array("code"=>"492", "name"=>"lavender blue/white"),
            array("code"=>"493", "name"=>"dark red mm"),
            array("code"=>"494", "name"=>"silky gold"),
            array("code"=>"495", "name"=>"grayish blue me"),
            array("code"=>"496", "name"=>"Silky Gold Mettalic"),
            array("code"=>"497", "name"=>"Darky Steel Mica"),
            array("code"=>"498", "name"=>"Avant Garde Bronze Metallic"),
            array("code"=>"503", "name"=>"Crimson Spark R"),
            array("code"=>"506", "name"=>"Attitude Black Metallic"),
            array("code"=>"507", "name"=>"Nebula Blue Metallic"),
            array("code"=>"510", "name"=>"Blackish Ageha GF"),
            array("code"=>"515", "name"=>"Pure White"),
            array("code"=>"522", "name"=>"Deep Maroon Metallic"),
            array("code"=>"523", "name"=>"Granite Gray Metallic"),
            array("code"=>"524", "name"=>"Oxide Bronze ME"),
            array("code"=>"525", "name"=>"Metalic Magma Gray"),
            array("code"=>"526", "name"=>"Pearl Midnight Black"),
            array("code"=>"527", "name"=>"Granite Gray Metallic"),
            array("code"=>"528", "name"=>"Pearl Phoenix Red"),
            array("code"=>"529", "name"=>"Metalic Premium Silver"),
            array("code"=>"530", "name"=>"Platinum White Pearl MC"),
            array("code"=>"531", "name"=>"Platinum White Pearl MC"),
            array("code"=>"532", "name"=>"Metal Stream ME"),
            array("code"=>"533", "name"=>"Celestite Gray ME"),
            array("code"=>"534", "name"=>"Graphite Metallic"),
            array("code"=>"535", "name"=>"Graphite ME"),
            array("code"=>"537", "name"=>"NULLTRUFFLE MICA"),
            array("code"=>"540", "name"=>"TRUFFLE MICA"),
            array("code"=>"541", "name"=>"Precious White"),
            array("code"=>"544", "name"=>"Red Purple Pearl"),
            array("code"=>"545", "name"=>"Brownish Purple Pearl"),
            array("code"=>"546", "name"=>"Nebula Blue Metallic")
        );

        foreach ($colors as $color) {
            TraVehicleColor::updateOrCreate([
                'code' => $color['code']
            ], [
                'code' => $color['code'],
                'name' => $color['name'],
            ]);
        }
    }
}
